name: BankSystem CI Automation

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Lấy code từ repo về máy ảo

      - name: Set up JDK 17
        uses: actions/setup-java@v4 # Cài đặt Java 17
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven' # Giúp lần sau build nhanh hơn

      - name: Build and Test with Maven
        # Chạy kiểm tra code (Checkstyle), chạy Test và đóng gói (.jar)
        run: mvn clean package

      - name: Upload Build Artifact
        # Lưu trữ file .jar sau khi build thành công để tải về
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: BankSystem-Jar-File
          path: target/*.jar